### PR TITLE
aaaaaaaaa

### PR DESCRIPTION
**Pull request by cfgexe**

### CODE REVIEW

**Review by MaleVTuber — CHANGES_REQUESTED** [review]
pr crashes the client with a 404 error. Please fix it before resubmitting.

**Comment by cfgexe** [comment]
i somehow forgot to do the version.txt file, fixed now

**Comment by MaleVTuber** [comment]
please add a try/except to version control. It still crashes.

**Comment by MaleVTuber** [comment]
Instead of prompting the user to update and then crashing the client, you should look by release tags for the latest release and grab the binary. Or I can do it myself. Is this all you added?

**Comment by cfgexe** [comment]
should work now

**Comment by MaleVTuber** [comment]
nothing has changed. Is this all you wanted to push?

**Comment by cfgexe** [comment]
yes, for now

**Comment by MaleVTuber** [comment]
ok. I'm not going to merge this. There is literally 0 point in doing this. It does nothing, especially if the user can't get python scripts in the exe

**Comment by cfgexe** [comment]
ok

**Pull request closed without merging**
